### Login
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

> {% client.global.set("lu_token", response.body.access_token); %}

### Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "password",
  "email": "me@lu.com"
}

### Get Current User
GET http://localhost:8080/api/users/me
Authorization: Bearer {{lu_token}}

### Get User
GET http://localhost:8080/api/users/1
Authorization: Bearer {{lu_token}}


### Create Short URL
POST http://localhost:8080/api/urls
Content-Type: application/json
Authorization: Bearer {{lu_token}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expirationTime": "",
  "userId": 1
}


### Visit Short URL
// @no-redirect
GET http://localhost:8080/s/custom
