### Check Email
POST http://localhost:8080/auth/check-email
Content-Type: application/json

{
  "email": "test@example.com"
}

### Send Register Verification
POST http://localhost:8080/auth/register-verification
Content-Type: application/json

{
  "email": "test@example.com"
}

### Verify Email Before Register
POST http://localhost:8080/auth/register-verification/verify
Content-Type: application/json

{
  "email": "test@example.com",
  "verifyCode": "123456"
}

### Send Email Verification
POST http://localhost:8080/auth/email-verification
Content-Type: application/json

{
  "email": "test@example.com"
}

### Login
POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "email": "test@lu.com",
  "password": "password"
}

> {% client.global.set("lu_token", response.body.access_token); %}

### Signup
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "alice",
  "password": "passw0rd",
  "email": "me@lu.com",
  "verifyCode": "123456"
}

### Get Guest Id
GET http://localhost:8080/auth/guest-id

> {% client.global.set("guest_id", response.body.guestId); %}

### Get Current User
GET http://localhost:8080/users/me
Authorization: Bearer {{lu_token}}

### Get User
GET http://localhost:8080/users/1
Authorization: Bearer {{lu_token}}

### Migrate Data
POST http://localhost:8080/users/migrate
Authorization: Bearer {{lu_token}}
Content-Type: application/json

{
  "guestId": "{{guest_id}}"
}

### Update User
PUT http://localhost:8080/users
Authorization: Bearer {{lu_token}}
Content-Type: application/json

{
  "id": 1,
  "username": "updated_username",
  "email": "updated_email@example.com"
}

### Create Short URL by Guest
POST http://localhost:8080/links
Content-Type: application/json
Guest-Id: {{guest_id}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expiresAt": ""
}

### Get Short URL by Guest
GET http://localhost:8080/links/1
Guest-Id: {{guest_id}}

### Create Short URL
POST http://localhost:8080/links
Content-Type: application/json
Authorization: Bearer {{lu_token}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expiresAt": ""
}

### Query Short URL
GET http://localhost:8080/links?page=1&size=20&sort_by=short_url%2C-updated_at&q=custom
Authorization: Bearer {{lu_token}}

### Get Short URL
GET http://localhost:8080/links/1
Authorization: Bearer {{lu_token}}

### Delete Short URL
DELETE http://localhost:8080/links/1
Authorization: Bearer {{lu_token}}

### Get Link Counts by User
< {%
    const guest_id = client.global.get("guest_id") || "1";
    client.global.set("guest_id", guest_id)
%}
GET http://localhost:8080/links/counts
Authorization: Bearer {{lu_token}}
Guest-Id: {{guest_id}} # 2 选 1，优先级不如 Authorization 高

### Visit Short URL
// @no-redirect
GET http://localhost:8080/s/custom
