### Login
POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

> {% client.global.set("lu_token", response.body.accessToken); %}

### Signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "admin111",
  "password": "password",
  "email": "me@lu.com"
}

### Get Current User
GET http://localhost:8080/users/me
Authorization: Bearer {{lu_token}}

### Get User
GET http://localhost:8080/users/1
Authorization: Bearer {{lu_token}}

### Get User's Links
GET http://localhost:8080/users/1/links
Authorization: Bearer {{lu_token}}


### Create Short URL
POST http://localhost:8080/links
Content-Type: application/json
Authorization: Bearer {{lu_token}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expirationTime": "",
  "userId": 1
}


### Visit Short URL
// @no-redirect
GET http://localhost:8080/s/custom

### Get Access Records
GET http://localhost:8080/links/custom/access-records
Authorization: Bearer {{lu_token}}
