### Check Email
POST {{api_url}}/auth/check-email
Content-Type: application/json

{
  "email": "test@example.com"
}

### Send Register Verification
POST {{api_url}}/auth/register-verification
Content-Type: application/json

{
  "email": "test@example.com"
}

### Verify Email Before Register
POST {{api_url}}/auth/register-verification/verify
Content-Type: application/json

{
  "email": "test@example.com",
  "verifyCode": "123456"
}

### Send Email Verification
POST {{api_url}}/auth/email-verification
Content-Type: application/json

{
  "email": "test@example.com",
  "type": "LOGIN"
}

### Login
POST {{api_url}}/auth/token
Content-Type: application/json

{
  "email": "test@lu.com",
  "password": "password"
}

> {% client.global.set("lu_token", response.body.access_token); %}

### Admin Login
POST {{api_url}}/auth/token
Content-Type: application/json

{
  "email": "admin@lu.com",
  "password": "password"
}

> {% client.global.set("lu_token_admin", response.body.access_token); %}

### Signup
POST {{api_url}}/auth/register
Content-Type: application/json

{
  "username": "alice",
  "password": "passw0rd",
  "email": "me@lu.com",
  "verifyCode": "123456"
}

### Get Guest Id
GET {{api_url}}/auth/guest-id

> {% client.global.set("guest_id", response.body.guestId); %}

### Get Current User
GET {{api_url}}/users/me
Authorization: Bearer {{lu_token}}

### Get User
GET {{api_url}}/users/1
Authorization: Bearer {{lu_token}}

### Migrate Data
POST {{api_url}}/users/migrate
Authorization: Bearer {{lu_token}}
Content-Type: application/json

{
  "guestId": "{{guest_id}}"
}

### Update User
PUT {{api_url}}/users
Authorization: Bearer {{lu_token}}
Content-Type: application/json

{
  "id": 1,
  "username": "updated_username",
  "email": "updated_email@example.com"
}

### Create Short URL by Guest
POST {{api_url}}/links
Content-Type: application/json
Guest-Id: {{guest_id}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expiresAt": ""
}

### Get Short URL by Guest
GET {{api_url}}/links/1
Guest-Id: {{guest_id}}

### Create Short URL
POST {{api_url}}/links
Content-Type: application/json
Authorization: Bearer {{lu_token}}

{
  "originalUrl": "https://en.wikipedia.org/wiki/Cuckoo_filter",
  "customAlias": "custom",
  "expiresAt": ""
}

### Query Short URL
GET {{api_url}}/links?page=1&size=20&sort_by=short_url%2C-updated_at&q=custom
Authorization: Bearer {{lu_token}}

### Get Short URL
GET {{api_url}}/links/1
Authorization: Bearer {{lu_token}}

### Delete Short URL
DELETE {{api_url}}/links/1
Authorization: Bearer {{lu_token}}

### Get Link Counts by User
< {%
    const guest_id = client.global.get("guest_id") || "1";
    client.global.set("guest_id", guest_id)
%}
GET {{api_url}}/links/counts
Authorization: Bearer {{lu_token}}
Guest-Id: {{guest_id}} # 2 选 1，优先级不如 Authorization 高

### Visit Short URL
// @no-redirect
GET {{base_url}}/custom

### 初始化统计数据  ADMIN Only
POST {{api_url}}/statistics/analysis
Content-Type: application/json
Authorization: Bearer {{lu_token_admin}}

{
}

### 基本统计
GET {{api_url}}/statistics/basic?startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 时间线统计--天
GET {{api_url}}/statistics/timeseries?startTime=1577836800000&endTime=1730047301089&type=day
Authorization: Bearer {{lu_token}}

### 小时
GET {{api_url}}/statistics/timeseries?startTime=1577836800000&endTime=1730047301089&type=hour
Authorization: Bearer {{lu_token}}

### 国家统计
GET {{api_url}}/statistics/locations?startTime=1577836800000&endTime=1730047301089&type=country
Authorization: Bearer {{lu_token}}

### 地区统计
GET {{api_url}}/statistics/locations?startTime=1577836800000&endTime=1730047301089&type=region
Authorization: Bearer {{lu_token}}

### 城市统计
GET {{api_url}}/statistics/locations?startTime=1577836800000&endTime=1730047301089&type=city
Authorization: Bearer {{lu_token}}

### 来源统计
GET {{api_url}}/statistics/metrics?type=referer&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 来源类型统计
GET {{api_url}}/statistics/metrics?type=referer_type&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 语言统计
GET {{api_url}}/statistics/metrics?type=language&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 时区统计
GET {{api_url}}/statistics/metrics?type=timezone&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 设备统计
GET {{api_url}}/statistics/metrics?type=device&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 设备品牌
GET {{api_url}}/statistics/metrics?type=brand&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 设备类型统计
GET {{api_url}}/statistics/metrics?type=device_type&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 操作系统统计
GET {{api_url}}/statistics/metrics?type=os&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}

### 浏览器统计
GET {{api_url}}/statistics/metrics?type=browser&startTime=1577836800000&endTime=1730047301089
Authorization: Bearer {{lu_token}}
