spring:
  application:
    name: less-url
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: utf-8
  datasource:
    url: jdbc:h2:mem:less-url;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 192.168.31.19
  cache:
    redis:
      enable-statistics: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.xioshe.less.url.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
less:
  url:
    host: http://localhost:8080/
security:
  jwt:
    secret-key: 0ae90a665d936d3364043a53a7ee65a004172c2b9b211b467059ab2f3bc70663
    access-expiration-seconds: 3600
    refresh-expiration-seconds: 86400

decorator:
  datasource:
    enabled: true

#logging:
#  level:
#    org.springframework.security: trace
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    path: doc.html
    use-root-path: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  # 显示 actuator 接口
  show-actuator: true
