spring:
  application:
    name: less-url
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: utf-8
  datasource:
    url: jdbc:h2:mem:less-url;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 184706932d5a1e2b3f8c
            client-secret: 15790286e3c4d9a2f6b393080887a13652
            scope: email, public_profile
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.xioshe.less.url.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
less:
  url:
    host: http://localhost:8080/
security:
  jwt:
    secret-key: 0ae90a665d936d3364043a53a7ee65a004172c2b9b211b467059ab2f3bc70663
    expiration-seconds: 86400
logging:
  level:
    org.springframework.security: trace