# 请在启动参数中加入 --spring.profiles.active=mysql 以激活本配置文件
spring:
  datasource:
    url: "jdbc:mysql://192.168.31.19:3306/less_url?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: 123456
  sql:
    init:
      mode: always # 仅限测试环境使用，不适合生产环境。生产环境应该使用 flyway 或 liquibase 管理表结构