server:
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    enabled: true

spring:
  config:
    import: optional:file:.env[.properties] # 加载 .env 文件
  application:
    name: less-url
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: utf-8
  datasource:
    url: jdbc:h2:mem:less-url;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    cache-names: emails, links, users
    redis:
      enable-statistics: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    local-cache-scope: statement # 关闭一级缓存
    cache-enabled: false # 关闭二级缓存
  global-config:
    db-config:
      id-type: auto
      table-prefix: lu_
    banner: false
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.github.xioshe.less.url.entity
less:
  url:
    prefix: http://localhost:8080/
lu:
  base-url: ${BASE_URL:http://localhost:8080/}
  link:
    #      max-length: 6
    default-time-to-live-seconds: 86400 # 24h
security:
  jwt:
    access-expiration-seconds: 43200 # 12h
    refresh-expiration-seconds: 86400 # 24h
    key:
      secret: ${JWT_SECRET:0123456789abcdefghijklmnopqrstuv}
      rotation:
        cron: 0 0 0 * * ?

# 打印 SQL 详情，不要在生产环境使用
decorator:
  datasource:
    enabled: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    path: doc.html
    use-root-path: true
    enabled: true # 在生产环境要禁用
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  api-docs:
    enabled: true # 在生产环境要禁用

# 可观测性配置
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: health,info,loggers,metrics,prometheus
        include: "*" # 重新导入 pom 后就能正常显示 prometheus endpoint
  metrics:
    tags:
      application: ${spring.application.name}

version: @project.version@ # 获取 maven 中配置的项目版本信息