server:
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    enabled: true

spring:
  application:
    name: less-url
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: utf-8
  datasource:
    url: jdbc:h2:mem:less-url;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  data:
    redis:
      host: 192.168.31.19
  cache:
    redis:
      enable-statistics: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.xioshe.less.url.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
less:
  url:
    host: http://localhost:8080/
security:
  jwt:
    access-expiration-seconds: 3600
    refresh-expiration-seconds: 86400
    key:
      secret: cThIIoDvwdueQB468K5xDc5633seEFoq
      rotation:
        cron: 0 0 0 * * ? # 每天0点

# 打印 SQL 详情，不要在生产环境使用
decorator:
  datasource:
    enabled: true

#logging:
#  level:
#    org.springframework.security: trace
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    path: doc.html
    use-root-path: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'

# 可观测性配置
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: health,info,loggers,metrics,prometheus
        include: "*" # 重新导入 pom 后就能正常显示 prometheus endpoint
  metrics:
    tags:
      application: ${spring.application.name}

version: @project.version@