version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    deploy:
      restart_policy:
        condition: on-failure
  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure
  mysql8:
    image: mysql:8.0.30
    container_name: mysql8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/8.0/mysql-files:/var/lib/mysql-files
      - ./mysql/8.0/conf:/etc/mysql
      - ./mysql/8.0/logs:/var/log/mysql
      - ./mysql/8.0/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    deploy:
      restart_policy:
        condition: on-failure
  redis7:
    image: redis:7.2.4-alpine
    container_name: redis7
    ports:
      - "6379:6379"
    volumes:
      - ./redis/7/data:/data
      - ./redis/7/config/redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    deploy:
      restart_policy:
        condition: on-failure